### ISSUE TITLE
LUA error in 8.1

### ISSUE THREAD

**Issue by raysmith59** [skirmess/friends-share-resurrection#1]
12x FriendsShare\FriendsShare.lua:376: attempt to call global 'GetNumIgnores' (a nil value)
FriendsShare\FriendsShare.lua:376: in function `FriendsShare_SyncIgnoreList'
FriendsShare\FriendsShare.lua:465: in function `FriendsShare_SyncLists'
FriendsShare\FriendsShare.lua:491: in function `f'
FriendsShare\FriendsShare.lua:39: in function <FriendsShare\FriendsShare.lua:23>

Locals:
iItem = nil
currentFriend = nil
localIgnores = <table> {
}
retval = 0
(*temporary) = nil
(*temporary) = "attempt to call global 'GetNumIgnores' (a nil value)"
Realm = "Dalaran"

**Comment by raysmith59** [comment]
Fixed by changing line 376 to:

local numIgnores = C_FriendList.GetNumIgnores()

**Comment by skirmess** [comment]
Thank you! Fixed in version 30 which is available at curse
